FROM node:18-alpine as build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .


ARG VITE_API_BASE_URL

# Alterar a deacprdo com a necessidade
ENV VITE_API_BASE_URL=http://192.168.0.2:4001     

# Rodar o build da aplicação
RUN npm run build


FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

# Copiar os arquivos gerados no build para o diretório do Nginx
COPY --from=build /app/dist /usr/share/nginx/html
COPY --from=public /app/dist /usr/share/nginx/html

# Expor a porta 80
EXPOSE 80

# Rodar o Nginx para servir a aplicação
CMD ["nginx", "-g", "daemon off;"]
